name = "uno-ent-ad-targeting"
main = "src/index.js"
compatibility_date = "2024-09-23"

[[kv_namespaces]]
binding = "AD_CAMPAIGNS"
id = "1fb754cea64741afafb4f211b366ba2a"

[[routes]]
pattern = "unoent.com/*"
zone_name = "unoent.com"

[[routes]]
pattern = "www.unoent.com/*"
zone_name = "unoent.com"
